const express = require("express");
const hrRouter = express.Router();
const loginHrController = require("../../controllers/app/common/user.login.controller");
const {authUser} = require("../../middlewares/roleManagement");
const {loginUser} = loginHrController;
const {USER_TYPE_ENUM} = require("../../constants/models/Enums/signUpEnums");
const leaveRequestController = require("../../controllers/app/common/user.leaveRequest.controller");
const {userLeaveRequest} = leaveRequestController;
const userAuth = require("../../middlewares/authMiddleware");
const {verifyToken} = userAuth;
const employeeLeaveListController = require("../../controllers/app/hr/employeeLeaveList.controller");
const {employeeLeaveList} = employeeLeaveListController;
const allEmployeeList = require("../../controllers/app/common/user.employeeList.controller");
const {employeeList} = allEmployeeList;
const updateEmployeeLeaveStatus = require("../../controllers/app/common/user.UpdateLeaveStatus.controller");
const {updateLeaveStatus} = updateEmployeeLeaveStatus;
const leaveRequestStatus = require("../../middlewares/leaveStatusMiddleware");
const {leaveStatus} = leaveRequestStatus;
const addHoliday = require("../../controllers/app/hr/addPublicHoliday.controller");
const {addPublicHoliday} = addHoliday;
const editHoliday = require("../../controllers/app/hr/updatePublicHoliday.controller");
const {updatePublicHoliday} = editHoliday;
const holidayDeletion = require("../../controllers/app/hr/deletePublicHoliday.controller");
const {deletePublicHoliday} = holidayDeletion;
const employeeStatus = require("../../controllers/app/hr/updateEmployeeStatus.controller");
const {updateEmployeeStatus} = employeeStatus;
const holidayListController = require("../../controllers/app/common/publicHolidayList.controller");
const {holidayList} = holidayListController;
const removeEmployeeController = require("../../controllers/app/common/removeEmployee.controller");
const {removeEmployee} = removeEmployeeController;

hrRouter.post("/hr/login", authUser([USER_TYPE_ENUM.HR]), loginUser);
hrRouter.post("/hr/leave-request", verifyToken([USER_TYPE_ENUM.HR]), userLeaveRequest);
hrRouter.get("/hr/leave-request-list", verifyToken([USER_TYPE_ENUM.HR]), employeeLeaveList);
hrRouter.get("/hr/employee-list", verifyToken([USER_TYPE_ENUM.HR]), employeeList);
hrRouter.patch("/hr/update-employee-leave-status/:id", [verifyToken([USER_TYPE_ENUM.HR]), leaveStatus([USER_TYPE_ENUM.EMPLOYEE])], updateLeaveStatus);
hrRouter.post("/hr/add-public-holiday", verifyToken([USER_TYPE_ENUM.HR]), addPublicHoliday);
hrRouter.patch("/hr/edit-public-holiday/:id", verifyToken([USER_TYPE_ENUM.HR]), updatePublicHoliday);
hrRouter.delete("/hr/delete-public-holiday/:id", verifyToken([USER_TYPE_ENUM.HR]), deletePublicHoliday);
hrRouter.patch("/hr/edit-employee-status/:id", verifyToken([USER_TYPE_ENUM.HR]), updateEmployeeStatus);
hrRouter.get("/hr/public-holiday-list", verifyToken([USER_TYPE_ENUM.HR]), holidayList);
hrRouter.delete("/hr/remove-employee/:id", verifyToken([USER_TYPE_ENUM.HR]), removeEmployee);

module.exports = hrRouter;
